### ISSUE TITLE
Build: dr_wav.h is missing

### ISSUE THREAD

**Issue by slangbein** [jpcima/ysfx#13]
Linux Mint 20.2: followed yor build commands step by step
On the step:"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .."
compilation terminates with:
ysfx_audio_wav.cpp:31:10: fatal error: dr_wav.h: File not found
i guess, it is the dr_libs; right?
https://github.com/mackron/dr_libs
So, what to do?

**Comment by mynameismuhl** [comment]
It's a submodule.
If you do `git submodule update --init --recursive` 
(in ysfx dir) then git will clone it too.

**Comment by slangbein** [comment]
thanx, and yes, build process is working now
maybe you add the step to the description of the building steps:-)
