### ISSUE TITLE
Unable to build: error C3646: 'effect': unknown override specifier

### ISSUE THREAD

**Issue by nlaroche** [jpcima/ysfx#31]
I receive several "Unable to build: error C3646: 'effect': unknown override specifier" when attempting to build after a fresh clone on my win 10 machine. This happens right after cmake --build .

```
D:\BeatConnect\Plugin\ysfx\plugin\info.h(23,18): error C3646: 'effect': unknown override specifier (compiling source fi
le D:\BeatConnect\Plugin\ysfx\plugin\editor.cpp) [D:\BeatConnect\Plugin\ysfx\build\ysfx_plugin.vcxproj]
D:\BeatConnect\Plugin\ysfx\plugin\info.h(23,18): error C4430: missing type specifier - int assumed. Note: C++ does not
support default-int (compiling source file D:\BeatConnect\Plugin\ysfx\plugin\editor.cpp) [D:\BeatConnect\Plugin\ysfx\bu
ild\ysfx_plugin.vcxproj]
D:\BeatConnect\Plugin\ysfx\plugin\editor.cpp(130,30): error C2039: 'effect': is not a member of 'YsfxInfo' [D:\BeatConn
ect\Plugin\ysfx\build\ysfx_plugin.vcxproj]
```

**Comment by jpcima** [comment]
Sure, can you give details on what this build environment is?
I know as fact that it builds at least on Github Actions VS2019 configuration.
I'll give this a deeper look tomorrow.

**Comment by nlaroche** [comment]
Yup - Microsoft Visual Studio Community 2019, Version 16.6.0, win10/64bit machine. Let me know if you need any more info, and thanks! Exciting project

**Comment by jpcima** [comment]
No luck with reproducing this one. There was success on Win10 VS 16.8.2.
Neither Github Actions with both VS 2017 and 2019 configurations.

Is there anything else special about your build environment?

**Comment by nlaroche** [comment]
I pulled a clean version this morning, restarted my computer and tried again - this time it worked. I don't think I had rebooted after installs nasm , probably in the end it was just some system config issue. Thanks for the help and sorry for the non-issue!

**Comment by jpcima** [comment]
If a particular edit has fixed it, it might have been this recent commit: c3e468d
