### ISSUE TITLE
cmake.deps creates a dl target

### ISSUE THREAD

**Issue by jcelerier** [jpcima/ysfx#34]
This conflicts with the CMAKE_DL_LIBS variable: https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html

if another project uses CMAKE_DL_LIBS and includes ysfx, things may go awry due to dl now being a target:

```
CMake Error in 3rdparty/libossia/3rdparty/Servus/servus/CMakeLists.txt:
  export called with target "Servus_iface" which requires target "dl" that is
  not in any export set.


-- Generating done
CMake Error in 3rdparty/libossia/3rdparty/wiiuse/src/CMakeLists.txt:
  export called with target "wiiuse" which requires target "dl" that is not
  in any export set.
```

**Comment by jpcima** [comment]
It's fixed.

**Comment by jcelerier** [comment]
thanks !

**Comment by jpcima** [comment]
@jcelerier Good job with ossia score btw,
will you integrate the graphics as well?

**Comment by jcelerier** [comment]
yep, seems to work just fine on linux, just have to test on mac & win32 now :)
