### ISSUE TITLE
Adding one example plugin into the sources

### ISSUE THREAD

**Issue by trebmuh** [jpcima/ysfx#35]
This would allow to test "if it works or not" straight after building.

**Comment by jpcima** [comment]
You can use one of these which are listed under "JSFX Resources".
That's why this list is there. Do you think it as unsufficient?

The equalizer under the ReJJ repo is one moderately advanced example.

https://github.com/jpcima/ysfx#jsfx-resources

**Comment by trebmuh** [comment]
> You can use one of these which are listed under "JSFX Resources".

Yes, I know.


> That's why this list is there. Do you think it as unsufficient?

I think it would be more efficient to have a plug to try straight after building ysfx without the need to download from another repo.
Maybe adding ReJJ as a sub-repo would do the job. That way, no need to clone a second repo.

**Comment by jpcima** [comment]
I will not add sub-repos. This one is kept light on purpose. It's a runtime library for others to use.
The plugin is not the central element of ysfx, it was always meant to serve as reference implementation.

Second to that, I don't want to maintain a bundle of effects and track their updates.

Third, this installation will potentially be duplicate to other JSFX installations (that of Reaper) and such redundancy will be a source of confusion.

**Comment by trebmuh** [comment]
I see. Makes sense.
