### ISSUE TITLE
Support presets from RPL files

### ISSUE THREAD

**Issue by jpcima** [jpcima/ysfx#39]
Lots of these *.rpl files in the Geraint Luff collection

**Comment by jpcima** [comment]
Also, consider replacing the library's binary state format with that RE'd from reaper.
Let's make this a priority item, because the library has begin to get some use. (Carla, ossia-score)
This is ok with you @jcelerier ?

**Comment by jcelerier** [comment]
Absolutely, feel free to break stuff, I'm all for everything being in the best shape possible.
