### ISSUE TITLE
Small build issue in embedded JUCE

### ISSUE THREAD

**Issue by jcelerier** [jpcima/ysfx#59]
As reported here:

https://aur.archlinux.org/packages/ysfx-git#comment-872572

    /home/harv/.cache/yay/ysfx-git/src/ysfx-build/_deps/juce-src/modules/juce_gui_basics/windows/juce_ComponentPeer.h:504:18: error: ‘exchange’ is not a member of ‘std’

most likely this file lacks `#include <utility>`

**Comment by jpcima** [comment]
This is update to juce 7.0.0 in 543bc11.
IIRC this fixes the problem.

**Comment by jcelerier** [comment]
it does ! thanks !
