### ISSUE TITLE
Download links expired

### ISSUE THREAD

**Issue by fotisandstuff** [jpcima/ysfx#68]
Hello! The download links for the development builds no longer work.

**Comment by murl-digital** [comment]
Looks like the build artifacts expired

**Comment by visusys** [comment]
Chiming in here too, really want to use ysfx. Fixed links would be great.

**Comment by silvansky** [comment]
Build for macOS is here: https://github.com/jpcima/ysfx/issues/69#issuecomment-1429676422

**Comment by JoepVanlier** [comment]
Artefacts can be found here: https://github.com/JoepVanlier/ysfx/releases/tag/v0.0.2

**Comment by fotisandstuff** [comment]
> Artefacts can be found here: https://github.com/JoepVanlier/ysfx/releases/tag/v0.0.2
> 
> I did nothing to the code, just forked it and let the GH action run.

You're AWESOME, Saike :D
