### ISSUE TITLE
Search missing imports in the root folder recursively

### ISSUE THREAD

**Issue by jpcima** [jpcima/ysfx#9]

**Comment by junh1024** [comment]
I'm using v0.02 and these structures don't work, where JSFX depends on a library:

- Subfolder/JSFX.txt
- Subfolder/library.txt

and 

- Subfolder/JSFX.txt
- library.txt

Currently, the library HAS to be in the same folder as the JSFX for it to function on YSFX. (tested on windows in REAPER & S1)
